version: "3.9"
services:
  shiny:
    build:
      context: .
      target: base
    command: Rscript -e 'library(shiny); runApp("/src/cartographers/", port=3030, launch.browser=FALSE)'
    network_mode: 'host'
    ports:
      - "3030:3030"
    volumes:
      - .:/src/cartographers/
